export const GET_ROMANTIC_THEME_STARTED = 'GET_ROMANTIC_THEME_STARTED';
export const GET_ROMANTIC_THEME_SUCCESS = 'GET_ROMANTIC_THEME_SUCCESS';
export const GET_ROMANTIC_THEME_FAILURE = 'GET_ROMANTIC_THEME_FAILURE';
