export const GET_ADMIN_CLIENTS_STARTED = 'GET_ADMIN_CLIENTS_STARTED';
export const GET_ADMIN_CLIENTS_SUCCESS = 'GET_ADMIN_CLIENTS_SUCCESS';
export const GET_ADMIN_CLIENTS_FAILURE = 'GET_ADMIN_CLIENTS_FAILURE';
