export const GET_LEAVES_THEME_STARTED = 'GET_LEAVES_THEME_STARTED';
export const GET_LEAVES_THEME_SUCCESS = 'GET_LEAVES_THEME_SUCCESS';
export const GET_LEAVES_THEME_FAILURE = 'GET_LEAVES_THEME_FAILURE';
