export const GET_LEAVES_MAIN_SITE_STARTED = 'GET_LEAVES_MAIN_SITE_STARTED';
export const GET_LEAVES_MAIN_SITE_SUCCESS = 'GET_LEAVES_MAIN_SITE_SUCCESS';
export const GET_LEAVES_MAIN_SITE_FAILURE = 'GET_LEAVES_MAIN_SITE_FAILURE';
